// examples/vue/remote-vue-fullHeight/src/App.vue
<template>
  <div class="app-layout">
    <header>
      <h1>Vue 3 FullHeight Example</h1>
      <nav>
        <router-link to="/small">Small</router-link> |
        <router-link to="/scroll">Scroll Internal</router-link> |
        <router-link to="/tall">Tall Content</router-link>
      </nav>
    </header>
    <router-view />
  </div>
</template>

<style scoped>
.app-layout {
  display: grid;
  grid-template-rows: auto 1fr;
  height: 100vh;
}
</style>

// examples/react/remote-react-fullHeight/src/App.tsx
import { Link, Outlet } from 'react-router-dom'

export default function App() {
  return (
    <div className="app-layout">
      <header>
        <h1>React FullHeight Example</h1>
        <nav>
          <Link to="/small">Small</Link> | <Link to="/scroll">Scroll Internal</Link> | <Link to="/tall">Tall Content</Link>
        </nav>
      </header>
      <Outlet />
    </div>
  )
}
