// examples/vue/remote-vue-fullHeight/src/App.vue
<template>
  <div class="app-layout">
    <header>
      <h1>Vue 3 FullHeight Example</h1>
      <nav>
        <router-link to="/small">Small</router-link> |
        <router-link to="/scroll">Scroll Internal</router-link> |
        <router-link to="/tall">Tall Content</router-link>
      </nav>
    </header>
    <router-view />
  </div>
</template>

<style scoped>
.app-layout {
  display: grid;
  grid-template-rows: auto 1fr;
  height: 100vh;
}
</style>

// examples/angular/remote-angular-fullHeight/src/app/app.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { RouterOutlet, RouterLink } from '@angular/router';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, RouterLink],
  encapsulation: ViewEncapsulation.None,
  template: `
    <div class="app-layout">
      <header>
        <h1>Angular FullHeight Example</h1>
        <nav>
          <a routerLink="/small">Small</a> |
          <a routerLink="/scroll">Scroll Internal</a> |
          <a routerLink="/tall">Tall Content</a>
        </nav>
      </header>
      <router-outlet />
    </div>
  `,
  styles: [`
    .app-layout {
      display: grid;
      grid-template-rows: auto 1fr;
      height: 100vh;
    }
    .app-layout router-outlet {
      display: none;
    }
  `],
})
export class App {}
