// examples/angular/remote-angular-fullHeight/src/app/pages/scroll-internal.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-scroll-internal',
  template: `
    <div class="wrapper">
      <div>
        <h2>Scroll Internal</h2>
        <p>This page fills the available height and scrolls internally.</p>
      </div>
      @for (item of items; track item) {
        <p>Scrollable item {{ item }} — Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
      }
    </div>
  `,
  styles: [`
    :host {
      display: block;
      height: 100%;
      overflow: hidden;
    }
    .wrapper {
      height: 100%;
      overflow: auto;
    }
  `],
})
export class ScrollInternal {
  items = Array.from({ length: 30 }, (_, i) => i + 1);
}

// examples/react/remote-react-fullHeight/src/pages/ScrollInternal.tsx
export default function ScrollInternal() {
  return (
    <div style={{ height: '100%', overflow: 'auto' }}>
      <div>
        <h2>Scroll Internal</h2>
        <p>This page fills the available height and scrolls internally.</p>
      </div>
      {Array.from({ length: 30 }, (_, i) => (
        <p key={i}>
          Scrollable item {i + 1} — Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        </p>
      ))}
    </div>
  )
}
